### ISSUE TITLE
My Tickets 2.0 > "my-tickets-select-list.php" plugin >> add to cart button hidden

### ISSUE THREAD

**Issue by grobc** [joedolson/plugin-extensions#2]
After updating to V 2.0.0 the add to cart button will not be shown if I use the "my-tickets-select-list.php" plugin.
There is a CSS setting for the paragraph:
`<p style="display: none;">
						<button type="submit" name="mt_add_to_cart">In den Warenkorb<span class="mt-processing"><img src="https://xxxxxxx.de/wp-admin/images/spinner-2x.gif" alt="Bearbeite"></span></button>
						<input type="hidden" name="my-tickets" value="true">
						</p>`

Thanks
Carsten

**Comment by joedolson** [comment]
Well, that's pretty strange and unexpected. Exploring.
